services:
  db:
    container_name: "app_db"
    image: postgres
    restart: always
    volumes:
      - ./scripts/create:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_MULTIPLE_DATABASES: fragrance
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    container_name: "profileService"
    image: profile-service
    command: ["../../scripts/migrateAndStart.sh"]
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        - BUILD_VERSION=latest

    restart: always
    ports:
      - 5001:5000
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: profile

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/profile/health-check"]
      interval: 3s
      timeout: 5s
      retries: 5
